export const solutions = [
  {
    img: "/webdev.webp",
    imgtext: "/devscot1.webp",
    background: "linear-gradient(to bottom, #A78D5B, #5A4217)",
    id: "web",
    delay: "100",
    tools: ["React", "Angular", "Vue", "Node.js"],
    heading: "Web App Development",
    text: "We take care of your product on the development stage. We create custom web dev solutions for startups and enterprises. We listen to your ideas carefully and deliver the exact result.",
  },
  {
    img: "/mobiledev.webp",
    imgtext: "/devscot2.webp",
    background: "linear-gradient(to bottom, #42AA8C, #1C6D55)",
    id: "mobile",
    delay: "400",
    tools: ["React Native", "Swift", "Kotlin", "Java"],
    heading: "Mobile App Development",
    text: "We offer a full cycle of application design, integration and management services. Whether it is a consumer oriented app or a transformative enterprise-class solution.",
  },
  {
    img: "/ecommerce.webp",
    imgtext: "/devscot3.webp",
    background: "linear-gradient(to bottom, #37444C, #6B8696)",
    id: "ecommerce",
    delay: "700",
    tools: ["React", "Angular", "Vue", "Node.js"],
    heading: "E-commerce Solutions",
    text: "We will help you to create a user-friendly online store that will attract more clients. We provide custom e-commerce development services for businesses of all sizes.",
  },
  {
    img: "/uiux.webp",
    imgtext: "/devscot4.webp",
    background: "linear-gradient(to bottom, #421036, #BB491A)",
    id: "design",
    heading: "UI/UX Designs",
    tools: ["Figma", "Sketch", "Adobe XD", "InVision"],
    delay: "1000",
    text: "Eye-catching and user-friendly design is key to conversion. Our qualified UI/UX experts will bring your idea from concept to full-fledged responsive design with engaging elements created specially for your target audience.",
  },
  {
    img: "/3d.webp",
    imgtext: "/devscot5.webp",
    background: "linear-gradient(to bottom, #FFC801, #FFC801)",
    id: "3d",
    delay: "1100",
    tools: ["Blender", "Maya", "3ds Max", "Cinema 4D"],
    heading: "3D Graphics & Animations",
    text: "We will help you to create stunning visuals for your project. We provide 3D modeling, rendering, and animation services for various industries.",
  },
];
